Update lensgarden.json
archway-network/archway-ecosystem pull request #32
Opened 2023-08-22 18:59 UTC by CryptoChem0000

add logo

2023-08-23 08:54 UTC, lufa23 requested changes
hey, wouldn't it need to be` Lens.png` ?

2023-08-23 15:16 UTC, CryptoChem0000 commented
> 

is it case sensitive?

2023-08-24 20:59 UTC, eliasmpw commented
Yes, I just tested and it is case sensitive

2023-08-24 21:13 UTC, eliasmpw approved these changes

2023-08-25 10:32 UTC, lufa23 approved these changes

2023-08-25 10:32 UTC, merged